### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by mpp4manu** [woodenconsulting/react-js-diagrams#3]
Firstly I'll admit I am completely new to Node.JS, React, etc.  So it's okay to point an laugh.  I've spent about 7 hours trying to get this to work, so I finally thought I should post something.

I'm running node 7.5.0, npm 4.4.1, and webpack 2.3.1 on a Red Hat Linux EL 6 server.  I executed the simple instructions in the README and it fails completely.  After learning a bit more, I started installing things globally, which didn't resolve the problem.  I tried a complete "project" load (everything inside the react-js-diagrams folder, which didn't work.  And so on.  I'm not overly impressed with Node's dependency resolution model, but I'm in no position and lack the experience for that to have any weight.

This library is absolutely beautiful and I would love to be able to see it on a the server.  A colleague says I should just build it on a local workstation and browse to the resulting index file, but that's clearly not how we would use this.

Any help would be appreciated. 

Thanks.

Michael

```
> react-js-diagrams@2.4.5 start /usr/lib/node_modules/react-js-diagrams
> babel-node server.js --presets es2015,es2016,es2017,stage-0

Listening at http://localhost:3000/
webpack built ad8d62129e39bdf6cdc7 in 3980ms
Version: webpack 2.2.1
Time: 3980ms
        Asset     Size  Chunks                    Chunk Names
bundle.js.map  1.15 MB       0  [emitted]         bundle
    bundle.js   958 kB       0  [emitted]  [big]  bundle
     demo4.js   390 kB       2  [emitted]  [big]  demo4
     demo3.js   390 kB       3  [emitted]  [big]  demo3
     demo2.js   390 kB       4  [emitted]  [big]  demo2
     demo1.js   390 kB       5  [emitted]  [big]  demo1
     demos.js   390 kB       1  [emitted]  [big]  demos
 demos.js.map   475 kB       1  [emitted]         demos
 demo4.js.map   475 kB       2  [emitted]         demo4
 demo3.js.map   476 kB       3  [emitted]         demo3
 demo2.js.map   476 kB       4  [emitted]         demo2
 demo1.js.map   476 kB       5  [emitted]         demo1

ERROR in ./demos/index.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/demos/index.js Unexpected token (11:6)
You may need an appropriate loader to handle this file type.
|   const render = Component =>
|     ReactDOM.render(
|       <AppContainer>
|         <Component />
|       </AppContainer>,
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/index.js

ERROR in ./demos/demo1/index.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/demos/demo1/index.js Unexpected token (108:10)
You may need an appropriate loader to handle this file type.
|
|     // Render the canvas
|       return <RJD.DiagramWidget diagramEngine={engine} />;
|   }
| }
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/demo1/index.js

ERROR in ./demos/demo2/index.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/demos/demo2/index.js Unexpected token (117:10)
You may need an appropriate loader to handle this file type.
|
|     // Render the canvas
|       return <RJD.DiagramWidget diagramEngine={engine} />;
|   }
| }
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/demo2/index.js

ERROR in ./demos/demo3/index.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/demos/demo3/index.js Unexpected token (121:10)
You may need an appropriate loader to handle this file type.
|
|     // Render the canvas
|       return <RJD.DiagramWidget diagramEngine={engine} />;
|   }
| }
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/demo3/index.js

ERROR in ./demos/demo4/index.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/demos/demo4/index.js Unexpected token (12:6)
You may need an appropriate loader to handle this file type.
|   const render = Component => {
|     ReactDOM.render(
|       <Provider store={store}>
|         <AppContainer>
|           <Component />
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./demos/demo4/index.js

ERROR in ./src/WidgetFactories.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/WidgetFactories.js Unexpected token (17:11)
You may need an appropriate loader to handle this file type.
| export class NodeWidgetFactory extends WidgetFactory {
|   generateReactWidget(diagramEngine, node) {
|     return <DefaultNodeWidget node={node} diagramEngine={diagramEngine} />;
|   }
| }
 @ ./src/main.js 9:0-34
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/DiagramModel.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/DiagramModel.js Unexpected token (56:6)
You may need an appropriate loader to handle this file type.
|   serializeDiagram() {
|     return {
|       ...this.serialize(),
|       offsetX: this.offsetX,
|       offsetY: this.offsetY,
 @ ./src/main.js 13:0-31
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/Common.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/Common.js Unexpected token (17:6)
You may need an appropriate loader to handle this file type.
|   serialize() {
|     return {
|       ...super.serialize(),
|       _class: this.constructor.name,
|       selected: this.selected
 @ ./src/main.js 15:0-25
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultLinkFactory.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultLinkFactory.js Unexpected token (12:6)
You may need an appropriate loader to handle this file type.
|   generateReactWidget(diagramEngine, link) {
|     return (
|       <DefaultLinkWidget link={link} diagramEngine={diagramEngine} />
|     );
|   }
 @ ./src/main.js 1:0-46
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultLinkWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultLinkWidget.js Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|
| export class DefaultLinkWidget extends React.Component {
|   static defaultProps = {
|     color: 'black',
|     width: 3,
 @ ./src/main.js 2:0-45
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultNodeFactory.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultNodeFactory.js Unexpected token (12:6)
You may need an appropriate loader to handle this file type.
|   generateReactWidget(diagramEngine, node) {
|     return (
|       <DefaultNodeWidget node={node} diagramEngine={diagramEngine} />
|     );
|   }
 @ ./src/main.js 3:0-46
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultNodeWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultNodeWidget.js Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|
| export class DefaultNodeWidget extends React.Component {
|   static defaultProps = {
|     node: null,
|   };
 @ ./src/main.js 4:0-45
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultPortModel.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultPortModel.js Unexpected token (29:6)
You may need an appropriate loader to handle this file type.
|   serialize() {
|     return {
|       ...super.serialize(),
|       in: this.in,
|       label: this.label
 @ ./src/main.js 6:0-44
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/defaults/DefaultPortLabelWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/defaults/DefaultPortLabelWidget.js Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|
| export class DefaultPortLabel extends React.Component {
|   static defaultProps = {
|     in: true,
|     label: 'port'
 @ ./src/main.js 7:0-50
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/widgets/DiagramWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/widgets/DiagramWidget.js Unexpected token (9:22)
You may need an appropriate loader to handle this file type.
|
| export class DiagramWidget extends React.Component {
|   static defaultProps = {
|     onChange: () => {}
|   };
 @ ./src/main.js 19:0-40
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/widgets/LinkLayerWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/widgets/LinkLayerWidget.js Unexpected token (47:8)
You may need an appropriate loader to handle this file type.
|
|       return (
|         <LinkWidget {...props}>
|           {React.cloneElement(generatedLink, { pointAdded: this.props.pointAdded })}
|         </LinkWidget>
 @ ./src/main.js 20:0-42
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/widgets/NodeLayerWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/widgets/NodeLayerWidget.js Unexpected token (21:8)
You may need an appropriate loader to handle this file type.
|     const children = _.map(diagramModel.getNodes(), node => {
|       return (
|         <NodeWidget key={node.id} node={node} diagramEngine={diagramEngine}>
|           {this.props.diagramEngine.generateWidgetForNode(node)}
|         </NodeWidget>
 @ ./src/main.js 22:0-42
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/widgets/NodeWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/widgets/NodeWidget.js Unexpected token (20:6)
You may need an appropriate loader to handle this file type.
|
|     return (
|       <div {...props}>
|         {children}
|       </div>
 @ ./src/main.js 23:0-37
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js

ERROR in ./src/widgets/PortWidget.js
Module parse failed: /usr/lib/node_modules/react-js-diagrams/src/widgets/PortWidget.js Unexpected token (14:6)
You may need an appropriate loader to handle this file type.
|     const { name, node } = this.props;
|     return (
|       <div
|         className={'port' + (this.state.selected ? ' selected' : '')}
|         onMouseEnter={() => this.setState({ selected: true })}
 @ ./src/main.js 24:0-37
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/main.js
webpack: Failed to compile.
```

**Comment by woodenconsulting** [comment]
@mpp4manu I believe the issue was that I was referencing `babel-node` directly in my `npm start` script. You would have to have had that installed globally in order to get it to work, but I fixed the reference to point to the `node_modules` directory directly. Now, after an `npm install`, `npm start` should work fine without having that module globally installed. I published this fix on npm, version 2.4.6. Please let me know if this solves your issue, thanks!

**Comment by mpp4manu** [comment]
Firstly, thank you for the prompt response, Jeff.  It’s people like you who make the Open Source community work.

Sadly, however, it’s still not working.  After installing a few more modules, I tried to start it and got the following:

/home/m85763/node_modules/react-js-diagrams: npm start

> react-js-diagrams@2.4.6 start /home/m85763/node_modules/react-js-diagrams
> babel-node server.js --presets es2015,es2016,es2017,stage-0

/home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to /home/m85763/node_modules/babel-preset-es2015/lib/index.js which does not accept options. (While processing preset: "/home/m85763/node_modules/babel-preset-es2015/lib/index.js") (While processing preset: "/home/m85763/node_modules/babel-preset-es2015/lib/index.js")
    at /home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/m85763/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/home/m85763/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/m85763/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/m85763/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-js-diagrams@2.4.6 start: `babel-node server.js --presets es2015,es2016,es2017,stage-0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-js-diagrams@2.4.6 start script 'babel-node server.js --presets es2015,es2016,es2017,stage-0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-js-diagrams package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js --presets es2015,es2016,es2017,stage-0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-js-diagrams
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-js-diagrams
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m85763/.npm/_logs/2017-03-27T14_30_56_195Z-debug.log

Contents of debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@4.4.1
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-js-diagrams@2.4.6~prestart: react-js-diagrams@2.4.6
6 silly lifecycle react-js-diagrams@2.4.6~prestart: no script for prestart, continuing
7 info lifecycle react-js-diagrams@2.4.6~start: react-js-diagrams@2.4.6
8 verbose lifecycle react-js-diagrams@2.4.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-js-diagrams@2.4.6~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/m85763/node_modules/react-js-diagrams/node_modules/.bin:/home/m85763/node_modules/.bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opt/camunda_maintenance_automation/bin
10 verbose lifecycle react-js-diagrams@2.4.6~start: CWD: /home/m85763/node_modules/react-js-diagrams
11 silly lifecycle react-js-diagrams@2.4.6~start: Args: [ '-c',
11 silly lifecycle   'babel-node server.js --presets es2015,es2016,es2017,stage-0' ]
12 silly lifecycle react-js-diagrams@2.4.6~start: Returned: code: 1  signal: null
13 info lifecycle react-js-diagrams@2.4.6~start: Failed to exec start script
14 verbose stack Error: react-js-diagrams@2.4.6 start: `babel-node server.js --presets es2015,es2016,es2017,stage-0`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-js-diagrams@2.4.6
16 verbose cwd /home/m85763/node_modules/react-js-diagrams
17 verbose Linux 2.6.32-642.1.1.el6.x86_64
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
19 verbose node v7.5.0
20 verbose npm  v4.4.1
21 error code ELIFECYCLE
22 error errno 1
23 error react-js-diagrams@2.4.6 start: `babel-node server.js --presets es2015,es2016,es2017,stage-0`
23 error Exit status 1
24 error Failed at the react-js-diagrams@2.4.6 start script 'babel-node server.js --presets es2015,es2016,es2017,stage-0'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the react-js-diagrams package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     babel-node server.js --presets es2015,es2016,es2017,stage-0
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs react-js-diagrams
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls react-js-diagrams
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

I then simply ran “npm install” in the node_modules/react-js-diagrams directory.  This resulted in the errors above going away, but the original errors returned.  I can see the node server running and TCP port 3000 is up.  If I use curl against I get the following:

<!DOCTYPE html>
<html>
        <head>
                <title>React JS Diagrams</title>
                <meta charset="UTF-8">
                <script src="/dist/bundle.js"></script><script src="/dist/demos.js"></script>
        </head>
        <body>
    <div id='root'></div>
        </body>
</html>


I’m sure I’ve done something wrong somewhere as I’m so new to all of this.  I really appreciate your help.

Michael

**Comment by woodenconsulting** [comment]
@mpp4manu I've tested using the same node / npm versions and everything works fine for me. It sounds like you're getting errors when including this in your project?

What happens if you just `git clone` react-js-diagrams directly and run the following commands in that directory?

- `npm install`
- `npm start`

Another thing you can try is to uninstall all global modules and run the above again (after deleting the `node_modules` directory from react-js-diagrams.

Alternatively, you can run `webpack` instead of `npm start` to build the bundles and browse the demos on the file system. I wish I could be of more help, but I cannot reproduce this.

**Comment by mpp4manu** [comment]
Sadly, this also failed.  I’m not using it in a project yet. I just want to see the demos work.  The issues below were typical early in my attempts to build this.  After a long period of trial and error, I finally got a build back then.  However, it would not start as shown in the errors from my original post.

See the details from trying your suggestion below.  I apologize in advance if I’m doing something stupid and wasting your time.

/var/tmp/reactjs_2# git https://github.com/woodenconsulting/react-js-diagrams.git
git: 'https://github.com/woodenconsulting/react-js-diagrams.git' is not a git command. See 'git --help'.
roaapbpo02:/var/tmp/reactjs_2# git clone
roaapbpo02:/var/tmp/reactjs_2# rm -r react-js-diagrams
roaapbpo02:/var/tmp/reactjs_2# git clone https://github.com/woodenconsulting/react-js-diagrams.git
Initialized empty Git repository in /var/tmp/reactjs_2/react-js-diagrams/.git/
remote: Counting objects: 643, done.
remote: Compressing objects: 100% (338/338), done.
remote: Total 643 (delta 397), reused 549 (delta 303), pack-reused 0
Receiving objects: 100% (643/643), 4.77 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (397/397), done.

/var/tmp/reactjs_2/react-js-diagrams# npm install
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> node-sass@4.5.0 install /var/tmp/reactjs_2/react-js-diagrams/node_modules/node-sass
> node scripts/install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/var/tmp/reactjs_2/react-js-diagrams/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
react-js-diagrams@3.0.1 /var/tmp/reactjs_2/react-js-diagrams
├─┬ babel-cli@6.24.0
│ ├── babel-polyfill@6.23.0
│ ├─┬ babel-register@6.24.0
│ │ ├─┬ home-or-tmp@2.0.0
│ │ │ ├── os-homedir@1.0.2
│ │ │ └── os-tmpdir@1.0.2
│ │ └── source-map-support@0.4.14
│ ├─┬ chokidar@1.6.1
│ │ ├─┬ anymatch@1.3.0
│ │ │ ├── arrify@1.0.1
│ │ │ └─┬ micromatch@2.3.11
│ │ │   ├─┬ arr-diff@2.0.0
│ │ │   │ └── arr-flatten@1.0.1
│ │ │   ├── array-unique@0.2.1
│ │ │   ├─┬ braces@1.8.5
│ │ │   │ ├─┬ expand-range@1.8.2
│ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │   │ │   ├── is-number@2.1.0
│ │ │   │ │   ├── isobject@2.1.0
│ │ │   │ │   └── randomatic@1.1.6
│ │ │   │ ├── preserve@0.2.0
│ │ │   │ └── repeat-element@1.1.2
│ │ │   ├─┬ expand-brackets@0.1.5
│ │ │   │ └── is-posix-bracket@0.1.1
│ │ │   ├── extglob@0.3.2
│ │ │   ├── filename-regex@2.0.0
│ │ │   ├─┬ kind-of@3.1.0
│ │ │   │ └── is-buffer@1.1.5
│ │ │   ├── normalize-path@2.0.1
│ │ │   ├─┬ object.omit@2.0.1
│ │ │   │ ├─┬ for-own@0.1.5
│ │ │   │ │ └── for-in@1.0.2
│ │ │   │ └── is-extendable@0.1.1
│ │ │   ├─┬ parse-glob@3.0.4
│ │ │   │ ├── glob-base@0.3.0
│ │ │   │ └── is-dotfile@1.0.2
│ │ │   └─┬ regex-cache@0.4.3
│ │ │     ├── is-equal-shallow@0.1.3
│ │ │     └── is-primitive@2.0.0
│ │ ├── async-each@1.0.1
│ │ ├── glob-parent@2.0.0
│ │ ├── inherits@2.0.3
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.8.0
│ │ ├─┬ is-glob@2.0.1
│ │ │ └── is-extglob@1.0.0
│ │ └─┬ readdirp@2.1.0
│ │   └── set-immediate-shim@1.0.1
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├── convert-source-map@1.5.0
│ ├── fs-readdir-recursive@1.0.0
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ └── once@1.4.0
│ ├─┬ output-file-sync@1.1.2
│ │ └── graceful-fs@4.1.11
│ ├── path-is-absolute@1.0.1
│ ├── slash@1.0.0
│ ├── source-map@0.5.6
│ └─┬ v8flags@2.0.11
│   └── user-home@1.1.1
├─┬ babel-core@6.24.0
│ ├─┬ babel-code-frame@6.22.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├── has-ansi@2.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├── esutils@2.0.2
│ │ └── js-tokens@3.0.1
│ ├─┬ babel-generator@6.24.0
│ │ ├─┬ detect-indent@4.0.0
│ │ │ └─┬ repeating@2.0.1
│ │ │   └── is-finite@1.0.2
│ │ ├── jsesc@1.3.0
│ │ └── trim-right@1.0.1
│ ├── babel-helpers@6.23.0
│ ├── babel-messages@6.23.0
│ ├── babel-template@6.23.0
│ ├─┬ babel-traverse@6.23.1
│ │ └── globals@9.17.0
│ ├─┬ babel-types@6.23.0
│ │ └── to-fast-properties@1.0.2
│ ├── babylon@6.16.1
│ ├─┬ debug@2.6.3
│ │ └── ms@0.7.2
│ ├── json5@0.5.1
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ └── private@0.1.7
├─┬ babel-loader@6.4.1
│ ├─┬ find-cache-dir@0.1.1
│ │ ├── commondir@1.0.1
│ │ └─┬ pkg-dir@1.0.0
│ │   └─┬ find-up@1.1.2
│ │     ├── path-exists@2.1.0
│ │     └─┬ pinkie-promise@2.0.1
│ │       └── pinkie@2.0.4
│ ├─┬ loader-utils@0.2.17
│ │ ├── big.js@3.1.3
│ │ └── emojis-list@2.1.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── object-assign@4.1.1
├── babel-plugin-add-module-exports@0.2.1
├─┬ babel-plugin-transform-decorators-legacy@1.3.4
│ └── babel-plugin-syntax-decorators@6.13.0
├── babel-plugin-transform-runtime@6.23.0
├─┬ babel-preset-es2015@6.24.0
│ ├── babel-plugin-check-es2015-constants@6.22.0
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
│ ├── babel-plugin-transform-es2015-block-scoping@6.23.0
│ ├─┬ babel-plugin-transform-es2015-classes@6.23.0
│ │ ├── babel-helper-define-map@6.23.0
│ │ ├── babel-helper-function-name@6.23.0
│ │ ├── babel-helper-optimise-call-expression@6.23.0
│ │ └── babel-helper-replace-supers@6.23.0
│ ├── babel-plugin-transform-es2015-computed-properties@6.22.0
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.22.0
│ ├── babel-plugin-transform-es2015-for-of@6.23.0
│ ├── babel-plugin-transform-es2015-function-name@6.22.0
│ ├── babel-plugin-transform-es2015-literals@6.22.0
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.0
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.24.0
│ │ └── babel-plugin-transform-strict-mode@6.22.0
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.23.0
│ │ └── babel-helper-hoist-variables@6.22.0
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.0
│ ├── babel-plugin-transform-es2015-object-super@6.22.0
│ ├─┬ babel-plugin-transform-es2015-parameters@6.23.0
│ │ ├── babel-helper-call-delegate@6.22.0
│ │ └── babel-helper-get-function-arity@6.22.0
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.22.0
│ ├── babel-plugin-transform-es2015-spread@6.22.0
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.22.0
│ │ └── babel-helper-regex@6.22.0
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.22.0
│ │ └─┬ regexpu-core@2.0.0
│ │   ├── regenerate@1.3.2
│ │   ├── regjsgen@0.2.0
│ │   └─┬ regjsparser@0.1.5
│ │     └── jsesc@0.5.0
│ └─┬ babel-plugin-transform-regenerator@6.22.0
│   └── regenerator-transform@0.9.8
├─┬ babel-preset-es2016@6.22.0
│ └─┬ babel-plugin-transform-exponentiation-operator@6.22.0
│   ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.22.0
│   │ └── babel-helper-explode-assignable-expression@6.22.0
│   └── babel-plugin-syntax-exponentiation-operator@6.13.0
├─┬ babel-preset-es2017@6.22.0
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
│ └─┬ babel-plugin-transform-async-to-generator@6.22.0
│   ├── babel-helper-remap-async-to-generator@6.22.0
│   └── babel-plugin-syntax-async-functions@6.13.0
├─┬ babel-preset-react@6.23.0
│ ├── babel-plugin-syntax-jsx@6.18.0
│ ├── babel-plugin-transform-react-display-name@6.23.0
│ ├─┬ babel-plugin-transform-react-jsx@6.23.0
│ │ └── babel-helper-builder-react-jsx@6.23.0
│ ├── babel-plugin-transform-react-jsx-self@6.22.0
│ ├── babel-plugin-transform-react-jsx-source@6.22.0
│ └─┬ babel-preset-flow@6.23.0
│   └─┬ babel-plugin-transform-flow-strip-types@6.22.0
│     └── babel-plugin-syntax-flow@6.18.0
├─┬ babel-preset-stage-0@6.22.0
│ ├─┬ babel-plugin-transform-do-expressions@6.22.0
│ │ └── babel-plugin-syntax-do-expressions@6.13.0
│ ├─┬ babel-plugin-transform-function-bind@6.22.0
│ │ └── babel-plugin-syntax-function-bind@6.13.0
│ └─┬ babel-preset-stage-1@6.22.0
│   ├─┬ babel-plugin-transform-class-constructor-call@6.22.0
│   │ └── babel-plugin-syntax-class-constructor-call@6.18.0
│   ├─┬ babel-plugin-transform-export-extensions@6.22.0
│   │ └── babel-plugin-syntax-export-extensions@6.13.0
│   └─┬ babel-preset-stage-2@6.22.0
│     ├── babel-plugin-syntax-dynamic-import@6.18.0
│     ├─┬ babel-plugin-transform-class-properties@6.23.0
│     │ └── babel-plugin-syntax-class-properties@6.13.0
│     ├─┬ babel-plugin-transform-decorators@6.22.0
│     │ └─┬ babel-helper-explode-class@6.22.0
│     │   └── babel-helper-bindify-decorators@6.22.0
│     └─┬ babel-preset-stage-3@6.22.0
│       ├─┬ babel-plugin-transform-async-generator-functions@6.22.0
│       │ └── babel-plugin-syntax-async-generators@6.13.0
│       └─┬ babel-plugin-transform-object-rest-spread@6.23.0
│         └── babel-plugin-syntax-object-rest-spread@6.13.0
├─┬ babel-runtime@6.23.0
│ ├── core-js@2.4.1
│ └── regenerator-runtime@0.10.3
├─┬ css-loader@0.26.1
│ ├─┬ css-selector-tokenizer@0.7.0
│ │ ├── cssesc@0.1.0
│ │ ├── fastparse@1.1.1
│ │ └── regexpu-core@1.0.0
│ ├─┬ cssnano@3.10.0
│ │ ├─┬ autoprefixer@6.7.7
│ │ │ ├─┬ browserslist@1.7.7
│ │ │ │ └── electron-to-chromium@1.3.2
│ │ │ ├── caniuse-db@1.0.30000646
│ │ │ ├── normalize-range@0.1.2
│ │ │ └── num2fraction@1.2.2
│ │ ├── decamelize@1.2.0
│ │ ├── defined@1.0.0
│ │ ├─┬ has@1.0.1
│ │ │ └── function-bind@1.1.0
│ │ ├─┬ postcss-calc@5.3.1
│ │ │ ├── postcss-message-helpers@2.0.0
│ │ │ └─┬ reduce-css-calc@1.3.0
│ │ │   ├── math-expression-evaluator@1.2.16
│ │ │   └── reduce-function-call@1.0.2
│ │ ├─┬ postcss-colormin@2.2.2
│ │ │ └─┬ colormin@1.1.2
│ │ │   ├─┬ color@0.11.4
│ │ │   │ ├── clone@1.0.2
│ │ │   │ ├─┬ color-convert@1.9.0
│ │ │   │ │ └── color-name@1.1.2
│ │ │   │ └── color-string@0.3.0
│ │ │   └── css-color-names@0.0.4
│ │ ├── postcss-convert-values@2.6.1
│ │ ├── postcss-discard-comments@2.0.4
│ │ ├── postcss-discard-duplicates@2.1.0
│ │ ├── postcss-discard-empty@2.1.0
│ │ ├── postcss-discard-overridden@0.1.1
│ │ ├─┬ postcss-discard-unused@2.2.3
│ │ │ └── uniqs@2.0.0
│ │ ├─┬ postcss-filter-plugins@2.0.2
│ │ │ └─┬ uniqid@4.1.1
│ │ │   └── macaddress@0.2.8
│ │ ├── postcss-merge-idents@2.1.7
│ │ ├── postcss-merge-longhand@2.0.2
│ │ ├─┬ postcss-merge-rules@2.1.2
│ │ │ ├─┬ caniuse-api@1.5.3
│ │ │ │ ├── lodash.memoize@4.1.2
│ │ │ │ └── lodash.uniq@4.5.0
│ │ │ ├─┬ postcss-selector-parser@2.2.3
│ │ │ │ ├── flatten@1.0.2
│ │ │ │ ├── indexes-of@1.0.1
│ │ │ │ └── uniq@1.0.1
│ │ │ └── vendors@1.0.1
│ │ ├── postcss-minify-font-values@1.0.5
│ │ ├── postcss-minify-gradients@1.0.5
│ │ ├─┬ postcss-minify-params@1.2.2
│ │ │ └── alphanum-sort@1.0.2
│ │ ├── postcss-minify-selectors@2.1.1
│ │ ├── postcss-normalize-charset@1.1.1
│ │ ├─┬ postcss-normalize-url@3.0.8
│ │ │ ├── is-absolute-url@2.1.0
│ │ │ └─┬ normalize-url@1.9.1
│ │ │   ├── prepend-http@1.0.4
│ │ │   ├─┬ query-string@4.3.2
│ │ │   │ └── strict-uri-encode@1.1.0
│ │ │   └─┬ sort-keys@1.1.2
│ │ │     └── is-plain-obj@1.1.0
│ │ ├── postcss-ordered-values@2.2.3
│ │ ├── postcss-reduce-idents@2.4.0
│ │ ├── postcss-reduce-initial@1.0.1
│ │ ├── postcss-reduce-transforms@1.0.4
│ │ ├─┬ postcss-svgo@2.1.6
│ │ │ ├─┬ is-svg@2.1.0
│ │ │ │ └── html-comment-regex@1.1.1
│ │ │ └─┬ svgo@0.7.2
│ │ │   ├─┬ coa@1.0.1
│ │ │   │ └── q@1.5.0
│ │ │   ├── colors@1.1.2
│ │ │   ├─┬ csso@2.3.2
│ │ │   │ └── clap@1.1.3
│ │ │   ├─┬ js-yaml@3.7.0
│ │ │   │ ├─┬ argparse@1.0.9
│ │ │   │ │ └── sprintf-js@1.0.3
│ │ │   │ └── esprima@2.7.3
│ │ │   ├── sax@1.2.2
│ │ │   └── whet.extend@0.9.9
│ │ ├── postcss-unique-selectors@2.0.2
│ │ ├── postcss-value-parser@3.3.0
│ │ └── postcss-zindex@2.2.0
│ ├── lodash.camelcase@4.3.0
│ ├─┬ postcss@5.2.16
│ │ ├── js-base64@2.1.9
│ │ └── supports-color@3.2.3
│ ├── postcss-modules-extract-imports@1.0.1
│ ├─┬ postcss-modules-local-by-default@1.1.1
│ │ └─┬ css-selector-tokenizer@0.6.0
│ │   └── regexpu-core@1.0.0
│ ├─┬ postcss-modules-scope@1.0.2
│ │ └─┬ css-selector-tokenizer@0.6.0
│ │   └── regexpu-core@1.0.0
│ ├─┬ postcss-modules-values@1.2.2
│ │ └── icss-replace-symbols@1.0.2
│ └── source-list-map@0.1.8
├─┬ express@4.15.2
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.15
│ │ │ └── mime-db@1.27.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.1
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.0
│ ├─┬ finalhandler@1.0.1
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.4
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.3.0
│ ├── qs@6.4.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.1
│ │ ├── debug@2.6.1
│ │ ├── destroy@1.0.4
│ │ └── http-errors@1.6.1
│ ├── serve-static@1.12.1
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.14
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.1
├── lodash@4.17.4
├─┬ react@15.4.2
│ ├─┬ fbjs@0.8.11
│ │ ├── core-js@1.2.7
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.6.3
│ │ │ │ ├─┬ encoding@0.1.12
│ │ │ │ │ └── iconv-lite@0.4.15
│ │ │ │ └── is-stream@1.1.0
│ │ │ └── whatwg-fetch@2.0.3
│ │ ├── promise@7.1.1
│ │ ├── setimmediate@1.0.5
│ │ └── ua-parser-js@0.7.12
│ └── loose-envify@1.3.1
├─┬ react-dnd@2.3.0
│ ├── disposables@1.0.1
│ ├─┬ dnd-core@2.3.0
│ │ └── asap@2.0.5
│ ├── hoist-non-react-statics@1.2.0
│ └── invariant@2.2.2
├── react-dnd-html5-backend@2.3.0
├── react-dom@15.4.2
├─┬ react-hot-loader@3.0.0-beta.6
│ ├─┬ global@4.3.1
│ │ ├─┬ min-document@2.19.0
│ │ │ └── dom-walk@0.1.1
│ │ └── process@0.5.2
│ ├── react-deep-force-update@2.0.1
│ ├── react-proxy@3.0.0-alpha.1
│ ├─┬ redbox-react@1.3.4
│ │ └─┬ error-stack-parser@1.3.6
│ │   └── stackframe@0.3.1
│ └─┬ source-map@0.4.4
│   └── amdefine@1.0.1
├─┬ react-redux@5.0.3
│ └── lodash-es@4.17.4
├─┬ redux@3.6.0
│ └── symbol-observable@1.0.4
├─┬ redux-logger@2.10.2
│ └── deep-diff@0.3.4
├── redux-undo@0.6.1
├─┬ sass-loader@6.0.0
│ ├── async@2.2.0
│ ├── lodash.tail@4.1.1
│ └── pify@2.3.0
├─┬ source-map-loader@0.1.6
│ ├── async@0.9.2
│ └── source-map@0.1.43
├── style-loader@0.13.1
├─┬ webpack@2.3.2
│ ├── acorn@4.0.11
│ ├── acorn-dynamic-import@2.0.2
│ ├─┬ ajv@4.11.5
│ │ ├── co@4.6.0
│ │ └─┬ json-stable-stringify@1.0.1
│ │   └── jsonify@0.0.0
│ ├── ajv-keywords@1.5.1
│ ├── enhanced-resolve@3.1.0
│ ├── interpret@1.0.2
│ ├── json-loader@0.5.4
│ ├── loader-runner@2.3.0
│ ├─┬ memory-fs@0.4.1
│ │ ├─┬ errno@0.1.4
│ │ │ └── prr@0.0.0
│ │ └─┬ readable-stream@2.2.6
│ │   ├── buffer-shims@1.0.0
│ │   ├── core-util-is@1.0.2
│ │   ├── isarray@1.0.0
│ │   ├── process-nextick-args@1.0.7
│ │   └── util-deprecate@1.0.2
│ ├─┬ node-libs-browser@2.0.0
│ │ ├── assert@1.4.1
│ │ ├─┬ browserify-zlib@0.1.4
│ │ │ └── pako@0.2.9
│ │ ├─┬ buffer@4.9.1
│ │ │ ├── base64-js@1.2.0
│ │ │ └── ieee754@1.1.8
│ │ ├─┬ console-browserify@1.1.0
│ │ │ └── date-now@0.1.4
│ │ ├── constants-browserify@1.0.0
│ │ ├─┬ crypto-browserify@3.11.0
│ │ │ ├─┬ browserify-cipher@1.0.0
│ │ │ │ ├─┬ browserify-aes@1.0.6
│ │ │ │ │ └── buffer-xor@1.0.3
│ │ │ │ ├─┬ browserify-des@1.0.0
│ │ │ │ │ └── des.js@1.0.0
│ │ │ │ └── evp_bytestokey@1.0.0
│ │ │ ├─┬ browserify-sign@4.0.4
│ │ │ │ ├── bn.js@4.11.6
│ │ │ │ ├── browserify-rsa@4.0.1
│ │ │ │ ├─┬ elliptic@6.4.0
│ │ │ │ │ ├── brorand@1.1.0
│ │ │ │ │ ├── hash.js@1.0.3
│ │ │ │ │ ├── hmac-drbg@1.0.0
│ │ │ │ │ ├── minimalistic-assert@1.0.0
│ │ │ │ │ └── minimalistic-crypto-utils@1.0.1
│ │ │ │ └─┬ parse-asn1@5.1.0
│ │ │ │   └── asn1.js@4.9.1
│ │ │ ├── create-ecdh@4.0.0
│ │ │ ├─┬ create-hash@1.1.2
│ │ │ │ ├── cipher-base@1.0.3
│ │ │ │ ├── ripemd160@1.0.1
│ │ │ │ └── sha.js@2.4.8
│ │ │ ├── create-hmac@1.1.4
│ │ │ ├─┬ diffie-hellman@5.0.2
│ │ │ │ └── miller-rabin@4.0.0
│ │ │ ├── pbkdf2@3.0.9
│ │ │ ├── public-encrypt@4.0.0
│ │ │ └── randombytes@2.0.3
│ │ ├── domain-browser@1.1.7
│ │ ├── events@1.1.1
│ │ ├── https-browserify@0.0.1
│ │ ├── os-browserify@0.2.1
│ │ ├── path-browserify@0.0.0
│ │ ├── process@0.11.9
│ │ ├── punycode@1.4.1
│ │ ├── querystring-es3@0.2.1
│ │ ├── stream-browserify@2.0.1
│ │ ├─┬ stream-http@2.6.3
│ │ │ ├── builtin-status-codes@3.0.0
│ │ │ ├── to-arraybuffer@1.0.1
│ │ │ └── xtend@4.0.1
│ │ ├── string_decoder@0.10.31
│ │ ├── timers-browserify@2.0.2
│ │ ├── tty-browserify@0.0.0
│ │ ├─┬ url@0.11.0
│ │ │ └── punycode@1.3.2
│ │ ├─┬ util@0.10.3
│ │ │ └── inherits@2.0.1
│ │ └─┬ vm-browserify@0.0.4
│ │   └── indexof@0.0.1
│ ├─┬ supports-color@3.2.3
│ │ └── has-flag@1.0.0
│ ├── tapable@0.2.6
│ ├─┬ uglify-js@2.8.18
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.10.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@2.1.0
│ │   │ ├─┬ center-align@0.1.3
│ │   │ │ ├─┬ align-text@0.1.4
│ │   │ │ │ ├── longest@1.0.1
│ │   │ │ │ └── repeat-string@1.6.1
│ │   │ │ └── lazy-cache@1.0.4
│ │   │ ├── right-align@0.1.3
│ │   │ └── wordwrap@0.0.2
│ │   └── window-size@0.1.0
│ ├── watchpack@1.3.1
│ ├─┬ webpack-sources@0.2.3
│ │ └── source-list-map@1.1.1
│ └─┬ yargs@6.6.0
│   ├── camelcase@3.0.0
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.1.0
│   ├── get-caller-file@1.0.2
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ read-pkg-up@1.0.1
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├─┬ parse-json@2.2.0
│   │   │ │ └─┬ error-ex@1.3.1
│   │   │ │   └── is-arrayish@0.2.1
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├─┬ normalize-package-data@2.3.6
│   │   │ ├── hosted-git-info@2.4.1
│   │   │ ├─┬ is-builtin-module@1.0.0
│   │   │ │ └── builtin-modules@1.1.1
│   │   │ ├── semver@5.3.0
│   │   │ └─┬ validate-npm-package-license@3.0.1
│   │   │   ├─┬ spdx-correct@1.0.2
│   │   │   │ └── spdx-license-ids@1.2.2
│   │   │   └── spdx-expression-parse@1.0.4
│   │   └── path-type@1.1.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── set-blocking@2.0.0
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ └─┬ is-fullwidth-code-point@1.0.0
│   │   └── number-is-nan@1.0.1
│   ├── which-module@1.0.0
│   ├── y18n@3.2.1
│   └── yargs-parser@4.2.1
├─┬ webpack-dev-middleware@1.10.1
│ └── mime@1.3.4
└─┬ webpack-hot-middleware@2.17.1
  ├── ansi-html@0.0.7
  ├── html-entities@1.2.0
  ├── querystring@0.2.0
  └─┬ strip-ansi@3.0.1
    └── ansi-regex@2.1.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-03-29T12_25_02_462Z-debug.log

I have attached the debug log.

/var/tmp/reactjs_2/react-js-diagrams# npm install node-sass
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> node-sass@4.5.0 install /var/tmp/reactjs_2/react-js-diagrams/node_modules/node-sass
> node scripts/install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/var/tmp/reactjs_2/react-js-diagrams/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-03-29T12_27_07_568Z-debug.log


I have attached the debug log.

I really appreciate your help here.

Michael

**Comment by woodenconsulting** [comment]
@mpp4manu - The only thing different from my tests is that you're on Red Hat Linux EL 6 and I've tested on Mac and Ubuntu, so I'm guessing the root cause is there. With that said, it looks like an issue now with `node-sass`.

Here are some steps you can try to solve the issue:

1) I recommend you downgrade your node version to 6.10.1 which is the current LTS. You can use [nvm](https://github.com/creationix/nvm) to make this process easier. I'd also make sure you have the corresponding npm LTS.

2) From the root directory of the repository, try rebuilding `node-sass` by running `npm rebuild node-sass`

3) If the above options don't work, wipe out the `node_modules` directory and try running `npm install --unsafe-perm` to rule out any permission issues.

**Comment by woodenconsulting** [comment]
closing this issue as it appears to be environmental

**Comment by mpp4manu** [comment]
We’ve still not had a chance to test this, but I suspect you’re right to close this.

Thank you for your prompt responses and help.

Michael Peoples (mp4783)
Global Customer Service BizOps Orchestration
Office: +1 614-886-0923
Mobile: +1 614-886-0923

Principal Applications Developer
mp4783@att.com<mailto:mp4783@att.com>
